In [ ]:
#to prevent colab to automatically disconnect
import IPython
from google.colab import output

display(IPython.display.Javascript('''
 function ClickConnect(){
   btn = document.querySelector("colab-connect-button")
   if (btn != null){
     console.log("Click colab-connect-button");
     btn.click()
     }

   btn = document.getElementById('ok')
   if (btn != null){
     console.log("Click reconnect");
     btn.click()
     }
  }

setInterval(ClickConnect,60000)
'''))

print("Done.")

Done.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Step 1:Importing Libraries and Installing Dependencies**

In [ ]:
pip install keras-self-attention

Collecting keras-self-attention
  Downloading keras-self-attention-0.51.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras-self-attention) (2.0.2)
Building wheels for collected packages: keras-self-attention
  Building wheel for keras-self-attention (setup.py) ... done
  Created wheel for keras-self-attention: filename=keras_self_attention-0.51.0-py3-none-any.whl size=18895 sha256=2021cc6dab0d0cd1e33551a57886e7cb4ddd350060f3e4b2fc1acdf00e060b5d
  Stored in directory: /root/.cache/pip/wheels/46/f9/96/709295c836133071c12a300729fed4027757f889c01695feea
Successfully built keras-self-attention
Installing collected packages: keras-self-attention
Successfully installed keras-self-attention-0.51.0

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.13.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.14.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
# For data processing
import numpy as np
import math
from math import sqrt

# For data processing and manipulation
import pandas as pd
import csv

# For date calculations
import datetime
import time

# For ploting data
import IPython
import IPython.display

import itertools
from itertools import cycle
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# For checking path
import os , gc
import csv
import json


from scipy.stats import hmean

from sklearn.metrics import mean_squared_error, mean_absolute_error

#tensorflow libs
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping , Callback
import tensorflow as tf
from tensorflow.keras import backend as K
from keras import backend

from tensorflow.keras.layers import *
from tensorflow.keras.layers import Dense , GRU ,Dropout , PReLU , RepeatVector ,TimeDistributed, Attention,LayerNormalization,Add
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.utils import to_categorical , plot_model
from tensorflow.keras import regularizers, constraints, initializers, activations
#from keras.layers.recurrent import Recurrent, _time_distributed_dense
from tensorflow.keras.layers import SimpleRNN as Recurrent
#from tensorflow.compat.v1.keras.layers import RNN

from tensorflow.keras.layers import InputSpec

from keras_self_attention import SeqSelfAttention
from tensorflow.keras.layers import Concatenate

from tensorflow.keras.layers import Input, LSTM, Dense, Dropout, Bidirectional, TimeDistributed, LayerNormalization, Add
from tensorflow.keras import layers


tf.get_logger().setLevel('ERROR')
mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

# **Step 2: Loading Dataset**

In [ ]:
#(paths in my personal drive)
model_save_path = r'/content/drive/MyDrive/Crime Prediction/LA/Project Tasks(Codes)/Forecasting(without weather dataset)/3.Crime Forecasting/Trained_model_Files'
dataset_path = r'/content/drive/MyDrive/Crime Prediction/LA/Project Tasks(Codes)/Forecasting(without weather dataset)/2.Preparing Dataset to feed Model/patrol_wise_crime_dataset'

In [ ]:
files = os.listdir(dataset_path)
files

['Central_1.csv',
 'Rampart_2.csv',
 'Southwest_3.csv',
 'Hollenbeck_4.csv',
 'Harbor_5.csv',
 'Hollywood_6.csv',
 'Wilshire_7.csv',
 'West LA_8.csv',
 'Van Nuys_9.csv',
 'West Valley_10.csv',
 'Northeast_11.csv',
 '77th Street_12.csv',
 'Newton_13.csv',
 'Pacific_14.csv',
 'N Hollywood_15.csv',
 'Foothill_16.csv',
 'Devonshire_17.csv',
 'Southeast_18.csv',
 'Mission_19.csv',
 'Olympic_20.csv',
 'Topanga_21.csv']

In [ ]:
#loading dataset
patrol_divisons = {}
dataset = {}
for file in files:
  name = file.split('_')[0]
  id = file.split('_')[1].split('.')[0]
  patrol_divisons[int(id)] = name
  dataset[int(id)] = pd.read_csv(os.path.join(dataset_path,file))


patrol_divisons = dict(sorted(patrol_divisons.items()))
patrol_divisons

{1: 'Central',
 2: 'Rampart',
 3: 'Southwest',
 4: 'Hollenbeck',
 5: 'Harbor',
 6: 'Hollywood',
 7: 'Wilshire',
 8: 'West LA',
 9: 'Van Nuys',
 10: 'West Valley',
 11: 'Northeast',
 12: '77th Street',
 13: 'Newton',
 14: 'Pacific',
 15: 'N Hollywood',
 16: 'Foothill',
 17: 'Devonshire',
 18: 'Southeast',
 19: 'Mission',
 20: 'Olympic',
 21: 'Topanga'}

In [ ]:
columns_in_dataset = dataset[1].columns
columns_in_dataset

Index(['Unnamed: 0', 'datetime', 'p_id', '1', '2', '3', '4', '5', '6', '7',
       '8', 'group 0', 'count', 'day sin', 'day cos', 'week sin', 'week cos',
       'year sin', 'year cos'],
      dtype='object')

In [ ]:
for key in dataset:
    if 'Unnamed: 0' in dataset[key].columns:
        dataset[key] = dataset[key].drop('Unnamed: 0', axis=1)

In [ ]:
dataset[1].head()

,datetime,p_id,1,2,3,4,5,6,7,8,group 0,count,day sin,day cos,week sin,week cos,year sin,year cos
0,2010-01-01 00:00:00,1,6.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,11.0,-4.416858e-12,1.000000e+00,0.781831,0.623490,0.005161,0.999987
1,2010-01-01 03:00:00,1,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,7.071068e-01,7.071068e-01,0.846724,0.532032,0.007311,0.999973
2,2010-01-01 06:00:00,1,0.0,0.0,0.0,12.0,1.0,0.0,0.0,1.0,0.0,14.0,1.000000e+00,6.980203e-12,0.900969,0.433884,0.009461,0.999955
3,2010-01-01 09:00:00,1,2.0,0.0,0.0,13.0,1.0,0.0,1.0,0.0,0.0,17.0,7.071068e-01,-7.071068e-01,0.943883,0.330279,0.011612,0.999933
4,2010-01-01 12:00:00,1,0.0,2.0,0.0,7.0,0.0,0.0,0.0,1.0,0.0,10.0,9.543547e-12,-1.000000e+00,0.974928,0.222521,0.013762,0.999905

In [ ]:
print(dataset[1]["count"].max())
print(dataset[1]["count"].min())

69.0
0.0

# **Step 3: Converting to Time Series data**

**Utility Functions**

In [ ]:
def train_test_val_split(dataset):
  columns_indices = {name:i for i,name in enumerate(dataset.columns)}
  n = len(dataset)

  #splitting dataset
  training_set = dataset[:int(n*0.7)]
  validation_set = dataset[int(n*0.7):int(n*0.9)]
  test_set = dataset[int(n*0.9):]

  num_features = dataset.shape[1]
  return training_set, validation_set, test_set, num_features, columns_indices

In [ ]:
class WindowGenerator():

    def __init__(self, input_width, label_width, shift,
               train_df, val_df, test_df,
               label_columns=None , shuffle=False , batch_size = 64):
        '''
        The __init__ method includes all the necessary logic for the input and label indices.
        Input:
            input_width : input width / window size
            label_width : output width
            shift : size of window shifting forward
            train_df : train dataset
            val_df : validation dataset
            test_df : test dataset
            label_columns ( Default = None) : Label Columns
            shuffle ( Default = False) : weather to shuffle data
            batch_size (Default = 64) : Batch Size
        Output: None
        Example :
            w2 = WindowGenerator(input_width=6, label_width=1, shift=1,
                     label_columns=['count'])
            w2

        '''
        # Store the raw data.
        self.train_df = train_df
        self.val_df = val_df
        self.test_df = test_df
        self.shuffle = shuffle
        self.batch_size = batch_size

        # Work out the label column indices.
        self.label_columns = label_columns
        if label_columns is not None:
            self.label_columns_indices = {name: i for i, name in
                                        enumerate(label_columns)}

        self.column_indices = {name: i for i, name in
                            enumerate(train_df.columns)}


        # Work out the window parameters.
        self.input_width = input_width
        self.label_width = label_width
        self.shift = shift

        self.total_window_size = input_width + shift

        self.input_slice = slice(0, input_width) #(start , stop)
        self.input_indices = np.arange(self.total_window_size)[self.input_slice]

        self.label_start = self.total_window_size - self.label_width
        self.labels_slice = slice(self.label_start, None)
        self.label_indices = np.arange(self.total_window_size)[self.labels_slice]

    def __repr__(self):
        return '\n'.join([
            f'Total window size: {self.total_window_size}',
            f'Input indices: {self.input_indices}',
            f'Label indices: {self.label_indices}',
            f'Label column name(s): {self.label_columns}'])

    def split_window(self, features):

        inputs = features[:, self.input_slice, :]
        labels = features[:, self.labels_slice, :]
        #taking only the labels that are presentin the label_columns
        if self.label_columns is not None:
            labels = tf.stack([labels[:, :, self.column_indices[name]] for name in self.label_columns],axis=-1)

        # Slicing doesn't preserve static shape information, so set the shapes
        # manually. This way the `tf.data.Datasets` are easier to inspect.
        inputs.set_shape([None, self.input_width, None])
        labels.set_shape([None, self.label_width, None])

        return inputs, labels



    def make_dataset(self, data):

        data = np.array(data, dtype=np.float32)
        ds = tf.keras.preprocessing.timeseries_dataset_from_array(
            data=data,
            targets=None,
            sequence_length=self.total_window_size,
            sequence_stride=1,
            shuffle=self.shuffle,
            batch_size=self.batch_size,)
        ds = ds.map(self.split_window)
        return ds


    def create_dataset2(self , map_df , reshape=True):
      x = []
      y = []
      for res in iter(map_df):
        inputs, labels = res
        if(len(inputs)==64):
          x.append(inputs)
          y.append(labels)

      x = np.array(x)
      y = np.array(y)
      if(reshape):
        x = x.reshape(-1, x.shape[-2] , x.shape[-1])
        y = y.reshape(-1 , y.shape[-2] , y.shape[-1])
      return x , y

    '''
    properties for accessing  training, validation and test data as tf.data.Datasets using the above make_dataset method.
    Also a standard example batch for easy access and plotting
    '''

    @property
    def train(self):
        return self.make_dataset(self.train_df)

    @property
    def val(self):
        return self.make_dataset(self.val_df)

    @property
    def test(self):
        return self.make_dataset(self.test_df)

In [ ]:
def create_data(train , test , val , columns):
    '''
    Create dataset from main train , test , val with given columns
    '''
    if(columns==None):
        columns = train.columns
    new_train = train[columns]
    new_test = test[columns]
    new_val = val[columns]
    return new_train , new_test , new_val

In [ ]:
def save_history(history , path):
    # convert the history.history dict to a pandas DataFrame:
    hist_df = pd.DataFrame(history.history)
    # or save to csv:
    hist_csv_file = path
    with open(hist_csv_file, mode='w') as f:
        hist_df.to_json(f)

def get_history(path):
	with open(path) as json_file:
		data = json.load(json_file)
		return data

def save_model_weights(model , path):
  model.save_weights(path)

Functions for Model Compiling and Fitting

In [ ]:
def compileModel(model):

        lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
          initial_learning_rate=1e-4,
          decay_steps=1000,
          decay_rate=0.96,
          staircase=True,
      )
        optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

        model.compile(loss=tf.losses.MeanAbsoluteError(),optimizer = optimizer,
                   metrics =[ tf.keras.metrics.RootMeanSquaredError(name='rmse'),
                              tf.keras.metrics.MeanAbsoluteError(name='mae')])
        return model

MAX_EPOCHS = 30

def fit(model,ROOTPATH, modelPath , historyPath , window=None, name=None , patience = 5):
    '''
    Compile and fit a model
    '''

    modelPathPar = os.path.join(ROOTPATH,modelPath)
    historyPathPar = os.path.join(ROOTPATH,historyPath)

    #Creating a file to store model and it's history
    if (name!=None):
        model_path = os.path.join(modelPathPar,name+".keras")
        history_path = os.path.join(historyPathPar,name+".json")

        if not os.path.exists(modelPathPar):
            os.makedirs(modelPathPar)
        if not os.path.exists(historyPathPar):
            os.makedirs(historyPathPar)

    if (name!=None and os.path.exists(model_path)):
      print("Loaded Pre Trained Model")
      modelOld = tf.keras.models.load_model(model_path)
      model.set_weights(modelOld.get_weights())
      del modelOld
      history = get_history(history_path)
      return model , history



    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=patience)

    history = model.fit(window.train, epochs=MAX_EPOCHS,batch_size = 64,validation_data=window.val,
                        callbacks=[early_stopping],verbose=1)


    if(name!=None):
      model.save(model_path)
      save_history(history , history_path)

    return model , history.history

Function to save  metric values

In [ ]:
def build_metrics_dataframe(test_metrics_dict, val_metrics_dict, patrol_divisions_dict):
    """
    Converts performance dictionaries into a structured DataFrame.

    Parameters:
        test_metrics_dict (dict): Dict of test evaluation results {division_id: [loss, rmse, mae]}
        val_metrics_dict (dict): Dict of val evaluation results {division_id: [loss, rmse, mae]}
        patrol_divisions_dict (dict): Dict mapping division_id to division name

    Returns:
        pd.DataFrame: DataFrame with division names as rows and metrics as columns
    """
    rows = []

    for div_id in test_metrics_dict.keys():
        div_name = patrol_divisions_dict[int(div_id)]
        test = test_metrics_dict[div_id]
        val = val_metrics_dict[div_id]

        rows.append({
            "Division": div_name,
            "test rmse": test[1],
            "test mae": test[2],
            "val rmse": val[1],
            "val mae": val[2]
        })

    df = pd.DataFrame(rows)
    df.set_index("Division", inplace=True)
    return df

In [ ]:
#without temperature
general_indexs = ['1', '2', '3', '4', '5', '6', '7','8', 'count',
           'day sin', 'day cos', 'week sin', 'week cos',
           'year sin', 'year cos', 'group 0']

x_col = ['day sin' , 'day cos' , 'year sin' , 'year cos' , 'week cos' , 'week sin' ,'datetime']

def generate_window(df_now, ret_test = 0):
    train_df , val_df , test_df , num_features_df , column_indices_df = train_test_val_split(df_now)
    train_df , test_df , val_df = create_data(train_df , test_df , val_df , general_indexs)
    y_col = []

    #storing label columns
    for i in train_df.columns:
        if (i in x_col):
            continue
        y_col.append(i)

    #creating window generator object
    wide_window_all = WindowGenerator(train_df=train_df, test_df=test_df , val_df=val_df,
        input_width=24, label_width=24, shift=1,
        label_columns=y_col)

    if (ret_test == 1):
      return wide_window_all, test_df
    else:
      return wide_window_all

**1.Multi Head Attention Bi GRU**

In [ ]:
# Input layer
inputs = keras.Input(shape=(24, 16), name="gru_input")

# First BiGRU layer
x = layers.Bidirectional(
    layers.GRU(128, return_sequences=True, activation='swish'),
    name="bigru1"
)(inputs)
x = layers.Dropout(0.3, name="dropout_bigru")(x)

# Multi-Head Attention Layer (Self-Attention)
attn_output = layers.MultiHeadAttention(
    num_heads=4, key_dim=32, name="multihead_attention_gru"
)(x, x)
attn_output = layers.Dropout(0.3, name="dropout_attention_gru")(attn_output)
attn_output = layers.LayerNormalization(epsilon=1e-6, name="attn_residual_norm_gru")(x + attn_output)  # Residual connection

# Feed-Forward Layer after attention
ff = layers.TimeDistributed(
    layers.Dense(64, activation='swish'), name="ff1_gru"
)(attn_output)
ff = layers.Dropout(0.3, name="dropout_ff_gru")(ff)

# Project attention output to match ff shape for residual connection
attn_proj = layers.TimeDistributed(
    layers.Dense(64), name="attn_proj_gru"
)(attn_output)

# Final residual + normalization
ff_output = layers.LayerNormalization(epsilon=1e-6, name="ff_residual_norm_gru")(attn_proj + ff)

# Final Dense output layer (per time step)
output = layers.TimeDistributed(
    layers.Dense(10), name="output_layer_gru"
)(ff_output)

# Define the model
mh_attn_bi_gru = keras.Model(inputs, output, name="BiGRU_MHAttention_Residual")
mh_attn_bi_gru.summary()

Model: "BiGRU_MHAttention_Residual"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ gru_input (InputLayer)    │ (None, 24, 16)         │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ bigru1 (Bidirectional)    │ (None, 24, 256)        │        112,128 │ gru_input[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_bigru (Dropout)   │ (None, 24, 256)        │              0 │ bigru1[0][0]           │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ multihead_attention_gru   │ (None, 24, 256)        │        131,712 │ dropout_bigru[0][0],   │
│ (MultiHeadAttention)      │                        │                │ dropout_bigru[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_attention_gru     │ (None, 24, 256)        │              0 │ multihead_attention_g… │
│ (Dropout)                 │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add (Add)                 │ (None, 24, 256)        │              0 │ dropout_bigru[0][0],   │
│                           │                        │                │ dropout_attention_gru… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attn_residual_norm_gru    │ (None, 24, 256)        │            512 │ add[0][0]              │
│ (LayerNormalization)      │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ ff1_gru (TimeDistributed) │ (None, 24, 64)         │         16,448 │ attn_residual_norm_gr… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attn_proj_gru             │ (None, 24, 64)         │         16,448 │ attn_residual_norm_gr… │
│ (TimeDistributed)         │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_ff_gru (Dropout)  │ (None, 24, 64)         │              0 │ ff1_gru[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add_1 (Add)               │ (None, 24, 64)         │              0 │ attn_proj_gru[0][0],   │
│                           │                        │                │ dropout_ff_gru[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ ff_residual_norm_gru      │ (None, 24, 64)         │            128 │ add_1[0][0]            │
│ (LayerNormalization)      │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_layer_gru          │ (None, 24, 10)         │            650 │ ff_residual_norm_gru[… │
│ (TimeDistributed)         │                        │                │                        │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 278,026 (1.06 MB)

 Trainable params: 278,026 (1.06 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
val_performance_of_mh_attn_bi_gru = {}
performance_of_mh_attn_bi_gru = {}
histories_of_mh_attn_bi_gru = {}
mh_attn_bi_gru_model = compileModel(mh_attn_bi_gru)
save_path = os.path.join(model_save_path,"Multi Head Attention Bi GRU")
for x in patrol_divisons.keys():
        wide_window_all = generate_window(dataset[x])
        print(x,patrol_divisons[x])
        x = str(x)
        trained_mh_attn_bi_gru_model , history  = fit(
            mh_attn_bi_gru_model,save_path, "mh_attn_bi_gru_model_files" , "mh_attn_bi_gru_history_files" , name='mh_attn_bi_gru_all_feature_'+x , window=wide_window_all)
        histories_of_mh_attn_bi_gru['bd_'+x] = history
        val_performance_of_mh_attn_bi_gru[x] = trained_mh_attn_bi_gru_model.evaluate(wide_window_all.val)
        performance_of_mh_attn_bi_gru[x] = trained_mh_attn_bi_gru_model.evaluate(wide_window_all.test)

1 Central
Epoch 1/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 44s 50ms/step - loss: 0.7299 - mae: 0.7299 - rmse: 1.1179 - val_loss: 0.7155 - val_mae: 0.7155 - val_rmse: 1.3701
Epoch 2/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 15ms/step - loss: 0.4727 - mae: 0.4727 - rmse: 0.8292 - val_loss: 0.6917 - val_mae: 0.6917 - val_rmse: 1.1175
Epoch 3/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.3958 - mae: 0.3958 - rmse: 0.6699 - val_loss: 0.4910 - val_mae: 0.4910 - val_rmse: 0.9096
Epoch 4/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.3238 - mae: 0.3238 - rmse: 0.5969 - val_loss: 0.4443 - val_mae: 0.4443 - val_rmse: 0.8140
Epoch 5/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.2916 - mae: 0.2916 - rmse: 0.5574 - val_loss: 0.4234 - val_mae: 0.4234 - val_rmse: 0.7771
Epoch 6/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.2602 - mae: 0.2602 - rmse: 0.5071 - val_loss: 0.4261 - val_mae: 0.4261 - val_rmse: 0.7546
Epoch 7/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.2563 - mae: 0.2563 - rmse: 0.5030 - val_loss: 0.4350 - val_mae: 0.4350 - val_rmse: 0.7975
Epoch 8/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 9s 13ms/step - loss: 0.2269 - mae: 0.2269 - rmse: 0.4628 - val_loss: 0.3005 - val_mae: 0.3005 - val_rmse: 0.6391
Epoch 9/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.2092 - mae: 0.2092 - rmse: 0.4446 - val_loss: 0.3078 - val_mae: 0.3078 - val_rmse: 0.6309
Epoch 10/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1970 - mae: 0.1970 - rmse: 0.4330 - val_loss: 0.2684 - val_mae: 0.2684 - val_rmse: 0.6053
Epoch 11/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1831 - mae: 0.1831 - rmse: 0.4190 - val_loss: 0.2788 - val_mae: 0.2788 - val_rmse: 0.6030
Epoch 12/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1870 - mae: 0.1870 - rmse: 0.4224 - val_loss: 0.2734 - val_mae: 0.2734 - val_rmse: 0.6262
Epoch 13/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1808 - mae: 0.1808 - rmse: 0.4176 - val_loss: 0.2293 - val_mae: 0.2293 - val_rmse: 0.5773
Epoch 14/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1624 - mae: 0.1624 - rmse: 0.4023 - val_loss: 0.2469 - val_mae: 0.2469 - val_rmse: 0.5787
Epoch 15/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.1607 - mae: 0.1607 - rmse: 0.3985 - val_loss: 0.2379 - val_mae: 0.2379 - val_rmse: 0.5633
Epoch 16/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1591 - mae: 0.1591 - rmse: 0.3929 - val_loss: 0.3038 - val_mae: 0.3038 - val_rmse: 0.6295
Epoch 17/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1615 - mae: 0.1615 - rmse: 0.3922 - val_loss: 0.2221 - val_mae: 0.2221 - val_rmse: 0.5608
Epoch 18/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1496 - mae: 0.1496 - rmse: 0.3797 - val_loss: 0.2430 - val_mae: 0.2430 - val_rmse: 0.5584
Epoch 19/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1483 - mae: 0.1483 - rmse: 0.3742 - val_loss: 0.2295 - val_mae: 0.2295 - val_rmse: 0.5511
Epoch 20/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.1435 - mae: 0.1435 - rmse: 0.3663 - val_loss: 0.2101 - val_mae: 0.2101 - val_rmse: 0.5312
Epoch 21/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1393 - mae: 0.1393 - rmse: 0.3609 - val_loss: 0.1721 - val_mae: 0.1721 - val_rmse: 0.4916
Epoch 22/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1355 - mae: 0.1355 - rmse: 0.3551 - val_loss: 0.1983 - val_mae: 0.1983 - val_rmse: 0.5056
Epoch 23/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1315 - mae: 0.1315 - rmse: 0.3519 - val_loss: 0.1692 - val_mae: 0.1692 - val_rmse: 0.4801
Epoch 24/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1307 - mae: 0.1307 - rmse: 0.3508 - val_loss: 0.1709 - val_mae: 0.1709 - val_rmse: 0.4888
Epoch 25/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1265 - mae: 0.1265 - rmse: 0.3469 - val_loss: 0.2083 - val_mae: 0.2083 - val_rmse: 0.5297
Epoch 26/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1302 - mae: 0.1302 - rmse: 0.3495 - val_loss: 0.1573 - val_mae: 0.1573 - val_rmse: 0.4703
Epoch 27/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.1256 - mae: 0.1256 - rmse: 0.3447 - val_loss: 0.1505 - val_mae: 0.1505 - val_rmse: 0.4627
Epoch 28/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1206 - mae: 0.1206 - rmse: 0.3407 - val_loss: 0.1735 - val_mae: 0.1735 - val_rmse: 0.4635
Epoch 29/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1285 - mae: 0.1285 - rmse: 0.3467 - val_loss: 0.1656 - val_mae: 0.1656 - val_rmse: 0.4806
Epoch 30/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1245 - mae: 0.1245 - rmse: 0.3442 - val_loss: 0.1847 - val_mae: 0.1847 - val_rmse: 0.4765
138/138 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1612 - mae: 0.1612 - rmse: 0.4229
69/69 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - loss: 0.2350 - mae: 0.2350 - rmse: 0.6879
2 Rampart
Epoch 1/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 22s 46ms/step - loss: 0.1248 - mae: 0.1248 - rmse: 0.3074 - val_loss: 0.1413 - val_mae: 0.1413 - val_rmse: 0.3477
Epoch 2/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - loss: 0.1303 - mae: 0.1303 - rmse: 0.3145 - val_loss: 0.1216 - val_mae: 0.1216 - val_rmse: 0.3398
Epoch 3/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1196 - mae: 0.1196 - rmse: 0.3064 - val_loss: 0.0908 - val_mae: 0.0908 - val_rmse: 0.3124
Epoch 4/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1186 - mae: 0.1186 - rmse: 0.3042 - val_loss: 0.1238 - val_mae: 0.1238 - val_rmse: 0.3362
Epoch 5/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1204 - mae: 0.1204 - rmse: 0.3059 - val_loss: 0.1021 - val_mae: 0.1021 - val_rmse: 0.3159
Epoch 6/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 0.1149 - mae: 0.1149 - rmse: 0.3020 - val_loss: 0.0943 - val_mae: 0.0943 - val_rmse: 0.3111
Epoch 7/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1178 - mae: 0.1178 - rmse: 0.3022 - val_loss: 0.0884 - val_mae: 0.0884 - val_rmse: 0.3107
Epoch 8/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.1137 - mae: 0.1137 - rmse: 0.3004 - val_loss: 0.0956 - val_mae: 0.0956 - val_rmse: 0.3142
Epoch 9/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1129 - mae: 0.1129 - rmse: 0.2997 - val_loss: 0.0952 - val_mae: 0.0952 - val_rmse: 0.3134
Epoch 10/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1123 - mae: 0.1123 - rmse: 0.2990 - val_loss: 0.0823 - val_mae: 0.0823 - val_rmse: 0.3057
Epoch 11/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.1105 - mae: 0.1105 - rmse: 0.2970 - val_loss: 0.0822 - val_mae: 0.0822 - val_rmse: 0.3058
Epoch 12/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1097 - mae: 0.1097 - rmse: 0.2972 - val_loss: 0.1247 - val_mae: 0.1247 - val_rmse: 0.3325
Epoch 13/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.1139 - mae: 0.1139 - rmse: 0.3001 - val_loss: 0.0998 - val_mae: 0.0998 - val_rmse: 0.3140
Epoch 14/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.1101 - mae: 0.1101 - rmse: 0.2972 - val_loss: 0.0992 - val_mae: 0.0992 - val_rmse: 0.3133
Epoch 15/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.1119 - mae: 0.1119 - rmse: 0.2975 - val_loss: 0.0795 - val_mae: 0.0795 - val_rmse: 0.3030
Epoch 16/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1078 - mae: 0.1078 - rmse: 0.2949 - val_loss: 0.1084 - val_mae: 0.1084 - val_rmse: 0.3165
Epoch 17/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1136 - mae: 0.1136 - rmse: 0.2986 - val_loss: 0.0924 - val_mae: 0.0924 - val_rmse: 0.3065
Epoch 18/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1087 - mae: 0.1087 - rmse: 0.2943 - val_loss: 0.0985 - val_mae: 0.0985 - val_rmse: 0.3119
Epoch 19/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1092 - mae: 0.1092 - rmse: 0.2942 - val_loss: 0.0885 - val_mae: 0.0885 - val_rmse: 0.3059
Epoch 20/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 11s 16ms/step - loss: 0.1088 - mae: 0.1088 - rmse: 0.2942 - val_loss: 0.0943 - val_mae: 0.0943 - val_rmse: 0.3087
138/138 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0872 - mae: 0.0872 - rmse: 0.2688
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.1088 - mae: 0.1088 - rmse: 0.3956
3 Southwest
Epoch 1/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - loss: 0.1552 - mae: 0.1552 - rmse: 0.4782 - val_loss: 0.1171 - val_mae: 0.1171 - val_rmse: 0.5040
Epoch 2/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1501 - mae: 0.1501 - rmse: 0.4646 - val_loss: 0.0974 - val_mae: 0.0974 - val_rmse: 0.4937
Epoch 3/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 8s 16ms/step - loss: 0.1462 - mae: 0.1462 - rmse: 0.4560 - val_loss: 0.1069 - val_mae: 0.1069 - val_rmse: 0.4927
Epoch 4/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.1455 - mae: 0.1455 - rmse: 0.4506 - val_loss: 0.1248 - val_mae: 0.1248 - val_rmse: 0.4970
Epoch 5/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1460 - mae: 0.1460 - rmse: 0.4474 - val_loss: 0.1015 - val_mae: 0.1015 - val_rmse: 0.4823
Epoch 6/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1432 - mae: 0.1432 - rmse: 0.4425 - val_loss: 0.1087 - val_mae: 0.1087 - val_rmse: 0.4834
Epoch 7/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1448 - mae: 0.1448 - rmse: 0.4412 - val_loss: 0.1214 - val_mae: 0.1214 - val_rmse: 0.4841
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1119 - mae: 0.1119 - rmse: 0.3381
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1254 - mae: 0.1254 - rmse: 0.3503
4 Hollenbeck
Epoch 1/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - loss: 0.1068 - mae: 0.1068 - rmse: 0.2746 - val_loss: 0.0653 - val_mae: 0.0653 - val_rmse: 0.2260
Epoch 2/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - loss: 0.0974 - mae: 0.0974 - rmse: 0.2640 - val_loss: 0.0625 - val_mae: 0.0625 - val_rmse: 0.2254
Epoch 3/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.0949 - mae: 0.0949 - rmse: 0.2622 - val_loss: 0.0644 - val_mae: 0.0644 - val_rmse: 0.2276
Epoch 4/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.0930 - mae: 0.0930 - rmse: 0.2620 - val_loss: 0.0710 - val_mae: 0.0710 - val_rmse: 0.2329
Epoch 5/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0928 - mae: 0.0928 - rmse: 0.2625 - val_loss: 0.0656 - val_mae: 0.0656 - val_rmse: 0.2290
Epoch 6/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.0936 - mae: 0.0936 - rmse: 0.2631 - val_loss: 0.0568 - val_mae: 0.0568 - val_rmse: 0.2281
Epoch 7/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.0901 - mae: 0.0901 - rmse: 0.2619 - val_loss: 0.0660 - val_mae: 0.0660 - val_rmse: 0.2324
Epoch 8/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.0905 - mae: 0.0905 - rmse: 0.2625 - val_loss: 0.0580 - val_mae: 0.0580 - val_rmse: 0.2299
Epoch 9/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.0890 - mae: 0.0890 - rmse: 0.2623 - val_loss: 0.0656 - val_mae: 0.0656 - val_rmse: 0.2323
Epoch 10/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.0919 - mae: 0.0919 - rmse: 0.2641 - val_loss: 0.0654 - val_mae: 0.0654 - val_rmse: 0.2345
Epoch 11/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.0890 - mae: 0.0890 - rmse: 0.2631 - val_loss: 0.0707 - val_mae: 0.0707 - val_rmse: 0.2371
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0688 - mae: 0.0688 - rmse: 0.2250
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0671 - mae: 0.0671 - rmse: 0.2082
5 Harbor
Epoch 1/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 22s 45ms/step - loss: 0.1038 - mae: 0.1038 - rmse: 0.3141 - val_loss: 0.0602 - val_mae: 0.0602 - val_rmse: 0.2479
Epoch 2/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 26s 15ms/step - loss: 0.1019 - mae: 0.1019 - rmse: 0.3109 - val_loss: 0.0625 - val_mae: 0.0625 - val_rmse: 0.2479
Epoch 3/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1022 - mae: 0.1022 - rmse: 0.3102 - val_loss: 0.0696 - val_mae: 0.0696 - val_rmse: 0.2495
Epoch 4/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.1033 - mae: 0.1033 - rmse: 0.3106 - val_loss: 0.0706 - val_mae: 0.0706 - val_rmse: 0.2474
Epoch 5/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 0.1022 - mae: 0.1022 - rmse: 0.3090 - val_loss: 0.0614 - val_mae: 0.0614 - val_rmse: 0.2467
Epoch 6/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.1006 - mae: 0.1006 - rmse: 0.3080 - val_loss: 0.0618 - val_mae: 0.0618 - val_rmse: 0.2464
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0622 - mae: 0.0622 - rmse: 0.2407
70/70 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step - loss: 0.0591 - mae: 0.0591 - rmse: 0.2159
6 Hollywood
Epoch 1/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - loss: 0.1126 - mae: 0.1126 - rmse: 0.3561 - val_loss: 0.0955 - val_mae: 0.0955 - val_rmse: 0.3167
Epoch 2/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - loss: 0.1119 - mae: 0.1119 - rmse: 0.3542 - val_loss: 0.0899 - val_mae: 0.0899 - val_rmse: 0.3121
Epoch 3/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1123 - mae: 0.1123 - rmse: 0.3538 - val_loss: 0.0988 - val_mae: 0.0988 - val_rmse: 0.3172
Epoch 4/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1117 - mae: 0.1117 - rmse: 0.3524 - val_loss: 0.0912 - val_mae: 0.0912 - val_rmse: 0.3122
Epoch 5/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1110 - mae: 0.1110 - rmse: 0.3517 - val_loss: 0.0869 - val_mae: 0.0869 - val_rmse: 0.3086
Epoch 6/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - loss: 0.1107 - mae: 0.1107 - rmse: 0.3510 - val_loss: 0.0871 - val_mae: 0.0871 - val_rmse: 0.3086
Epoch 7/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1106 - mae: 0.1106 - rmse: 0.3507 - val_loss: 0.0843 - val_mae: 0.0843 - val_rmse: 0.3067
Epoch 8/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 8s 16ms/step - loss: 0.1101 - mae: 0.1101 - rmse: 0.3497 - val_loss: 0.0840 - val_mae: 0.0840 - val_rmse: 0.3066
Epoch 9/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1101 - mae: 0.1101 - rmse: 0.3496 - val_loss: 0.0859 - val_mae: 0.0859 - val_rmse: 0.3069
Epoch 10/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1098 - mae: 0.1098 - rmse: 0.3491 - val_loss: 0.0832 - val_mae: 0.0832 - val_rmse: 0.3058
Epoch 11/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 11s 17ms/step - loss: 0.1095 - mae: 0.1095 - rmse: 0.3486 - val_loss: 0.0846 - val_mae: 0.0846 - val_rmse: 0.3058
Epoch 12/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1093 - mae: 0.1093 - rmse: 0.3484 - val_loss: 0.0824 - val_mae: 0.0824 - val_rmse: 0.3038
Epoch 13/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.1090 - mae: 0.1090 - rmse: 0.3483 - val_loss: 0.0858 - val_mae: 0.0858 - val_rmse: 0.3052
Epoch 14/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.1087 - mae: 0.1087 - rmse: 0.3479 - val_loss: 0.0833 - val_mae: 0.0833 - val_rmse: 0.3036
Epoch 15/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.1091 - mae: 0.1091 - rmse: 0.3479 - val_loss: 0.0870 - val_mae: 0.0870 - val_rmse: 0.3063
Epoch 16/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1090 - mae: 0.1090 - rmse: 0.3479 - val_loss: 0.0820 - val_mae: 0.0820 - val_rmse: 0.3046
Epoch 17/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1081 - mae: 0.1081 - rmse: 0.3473 - val_loss: 0.0829 - val_mae: 0.0829 - val_rmse: 0.3047
Epoch 18/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 11s 16ms/step - loss: 0.1079 - mae: 0.1079 - rmse: 0.3468 - val_loss: 0.0807 - val_mae: 0.0807 - val_rmse: 0.3037
Epoch 19/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.1079 - mae: 0.1079 - rmse: 0.3467 - val_loss: 0.0817 - val_mae: 0.0817 - val_rmse: 0.3040
Epoch 20/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.1080 - mae: 0.1080 - rmse: 0.3467 - val_loss: 0.0816 - val_mae: 0.0816 - val_rmse: 0.3031
Epoch 21/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.1077 - mae: 0.1077 - rmse: 0.3464 - val_loss: 0.0862 - val_mae: 0.0862 - val_rmse: 0.3059
Epoch 22/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 0.1078 - mae: 0.1078 - rmse: 0.3463 - val_loss: 0.0861 - val_mae: 0.0861 - val_rmse: 0.3055
Epoch 23/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - loss: 0.1075 - mae: 0.1075 - rmse: 0.3462 - val_loss: 0.0831 - val_mae: 0.0831 - val_rmse: 0.3043
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0796 - mae: 0.0796 - rmse: 0.2892
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - loss: 0.0748 - mae: 0.0748 - rmse: 0.2739
7 Wilshire
Epoch 1/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 22s 46ms/step - loss: 0.0928 - mae: 0.0928 - rmse: 0.2618 - val_loss: 0.0685 - val_mae: 0.0685 - val_rmse: 0.2646
Epoch 2/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0922 - mae: 0.0922 - rmse: 0.2614 - val_loss: 0.0678 - val_mae: 0.0678 - val_rmse: 0.2639
Epoch 3/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.0920 - mae: 0.0920 - rmse: 0.2611 - val_loss: 0.0674 - val_mae: 0.0674 - val_rmse: 0.2654
Epoch 4/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 0.0913 - mae: 0.0913 - rmse: 0.2608 - val_loss: 0.0663 - val_mae: 0.0663 - val_rmse: 0.2653
Epoch 5/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0910 - mae: 0.0910 - rmse: 0.2607 - val_loss: 0.0686 - val_mae: 0.0686 - val_rmse: 0.2667
Epoch 6/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0908 - mae: 0.0908 - rmse: 0.2607 - val_loss: 0.0681 - val_mae: 0.0681 - val_rmse: 0.2663
Epoch 7/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0907 - mae: 0.0907 - rmse: 0.2607 - val_loss: 0.0662 - val_mae: 0.0662 - val_rmse: 0.2654
Epoch 8/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.0905 - mae: 0.0905 - rmse: 0.2605 - val_loss: 0.0678 - val_mae: 0.0678 - val_rmse: 0.2651
Epoch 9/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.0905 - mae: 0.0905 - rmse: 0.2603 - val_loss: 0.0672 - val_mae: 0.0672 - val_rmse: 0.2652
Epoch 10/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.0906 - mae: 0.0906 - rmse: 0.2605 - val_loss: 0.0693 - val_mae: 0.0693 - val_rmse: 0.2674
Epoch 11/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 0.0903 - mae: 0.0903 - rmse: 0.2604 - val_loss: 0.0675 - val_mae: 0.0675 - val_rmse: 0.2660
Epoch 12/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 0.0900 - mae: 0.0900 - rmse: 0.2600 - val_loss: 0.0660 - val_mae: 0.0660 - val_rmse: 0.2659
Epoch 13/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.0898 - mae: 0.0898 - rmse: 0.2596 - val_loss: 0.0662 - val_mae: 0.0662 - val_rmse: 0.2653
Epoch 14/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 0.0897 - mae: 0.0897 - rmse: 0.2598 - val_loss: 0.0662 - val_mae: 0.0662 - val_rmse: 0.2655
Epoch 15/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 0.0895 - mae: 0.0895 - rmse: 0.2597 - val_loss: 0.0682 - val_mae: 0.0682 - val_rmse: 0.2668
Epoch 16/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 0.0896 - mae: 0.0896 - rmse: 0.2595 - val_loss: 0.0656 - val_mae: 0.0656 - val_rmse: 0.2651
Epoch 17/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - loss: 0.0895 - mae: 0.0895 - rmse: 0.2596 - val_loss: 0.0652 - val_mae: 0.0652 - val_rmse: 0.2649
Epoch 18/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 0.0892 - mae: 0.0892 - rmse: 0.2596 - val_loss: 0.0694 - val_mae: 0.0694 - val_rmse: 0.2672
Epoch 19/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0893 - mae: 0.0893 - rmse: 0.2595 - val_loss: 0.0650 - val_mae: 0.0650 - val_rmse: 0.2650
Epoch 20/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 0.0892 - mae: 0.0892 - rmse: 0.2594 - val_loss: 0.0645 - val_mae: 0.0645 - val_rmse: 0.2648
Epoch 21/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0890 - mae: 0.0890 - rmse: 0.2592 - val_loss: 0.0688 - val_mae: 0.0688 - val_rmse: 0.2665
Epoch 22/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 0.0890 - mae: 0.0890 - rmse: 0.2590 - val_loss: 0.0654 - val_mae: 0.0654 - val_rmse: 0.2651
Epoch 23/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0889 - mae: 0.0889 - rmse: 0.2592 - val_loss: 0.0653 - val_mae: 0.0653 - val_rmse: 0.2650
Epoch 24/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0886 - mae: 0.0886 - rmse: 0.2589 - val_loss: 0.0671 - val_mae: 0.0671 - val_rmse: 0.2662
Epoch 25/30
479/479 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 0.0886 - mae: 0.0886 - rmse: 0.2590 - val_loss: 0.0651 - val_mae: 0.0651 - val_rmse: 0.2651
137/137 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0602 - mae: 0.0602 - rmse: 0.2447

In [ ]:
# Call the function after training is done
mh_attn_bi_gru_results_df = build_metrics_dataframe(
     performance_of_mh_attn_bi_gru,
    val_performance_of_mh_attn_bi_gru,
    patrol_divisons
)
csv_path = os.path.join(save_path,"mh_attn_bi_gru_results_1.csv")
mh_attn_bi_gru_results_df.to_csv(csv_path)

In [ ]:
mh_attn_bi_gru_results_df.head(21)

             test rmse  test mae  val rmse   val mae
Division
Central       0.713613  0.223138  0.476545  0.184686
Rampart       0.403934  0.101825  0.308708  0.094344
Southwest     0.363826  0.115266  0.484089  0.121378
Hollenbeck    0.184826  0.061920  0.237104  0.070740
Harbor        0.194903  0.054310  0.246436  0.061823
Hollywood     0.250244  0.065559  0.304336  0.083097
Wilshire      0.227689  0.051474  0.265104  0.065106
West LA       0.202879  0.045108  0.256146  0.062406
Van Nuys      0.197093  0.045592  0.232320  0.055161
West Valley   0.200406  0.046906  0.247521  0.058092
Northeast     0.204468  0.049060  0.232873  0.055253
77th Street   0.248167  0.057787  0.502437  0.094807
Newton        0.283581  0.053346  0.321618  0.064149
Pacific       0.256991  0.057798  0.291949  0.073846
N Hollywood   0.353487  0.069939  0.273603  0.071418
Foothill      0.180614  0.037323  0.219847  0.048977
Devonshire    0.202407  0.042912  0.236928  0.054153
Southeast     0.227675  0.047052  0.477492  0.072559
Mission       0.191272  0.041105  0.278892  0.054432
Olympic       0.289643  0.052931  0.278927  0.063341
Topanga       0.193342  0.040955  0.236688  0.053660

**Testing model trained on Central patrol divison**

In [ ]:
model = load_model(r'/content/drive/MyDrive/Crime Prediction/LA/Project Tasks(Codes)/Forecasting/3.Multi-Modal Fusion/FLF/Trained_model_files/Multi Head Attention Bi GRU/mh_attn_bi_gru_model_files/mh_attn_bi_gru_all_feature_3.keras')

In [ ]:
wide_window = generate_window(dataset[3])

In [ ]:
test_data = wide_window.test

In [ ]:

# Unbatch and convert to NumPy arrays
x_test_list = []
y_test_list = []

for x, y in test_data.unbatch():
    x_test_list.append(x.numpy())
    y_test_list.append(y.numpy())

# Convert lists to NumPy arrays
x_test = np.array(x_test_list)
y_test = np.array(y_test_list)

print("x_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)

x_test shape: (4178, 24, 16)
y_test shape: (4178, 24, 10)

In [ ]:
# Get predicted y values
y_pred = model.predict(x_test)
y_pred = np.round(np.maximum(y_pred, 0))
print("y_pred shape:", y_pred.shape)

131/131 ━━━━━━━━━━━━━━━━━━━━ 8s 26ms/step
y_pred shape: (4178, 24, 10)

In [ ]:
# Number of samples you want to inspect
num_samples = 5

# Create a list to store the comparison DataFrames
comparison_list = []

# Loop over the first `num_samples`
for i in range(num_samples):
    true_vals = y_test[i]   # shape: (24, 10)
    pred_vals = y_pred[i]   # shape: (24, 10)

    # Column names for better context
    columns = ['1','2','3','4','5','6','7','8','Count','Group 0']  # Adjust if needed

    df_true = pd.DataFrame(true_vals, columns=[f"{col}" for col in columns])
    df_pred = pd.DataFrame(pred_vals, columns=[f"{col}" for col in columns])

    df_both = pd.concat([df_true, df_pred], axis=1)
    comparison_list.append(df_both)

# Combine all comparisons into one DataFrame
full_comparison = pd.concat(comparison_list, axis=0)

# Reset index
full_comparison.reset_index(drop=True, inplace=True)

In [ ]:
full_comparison.head()

,1,2,3,4,5,6,7,8,Count,Group 0,1,2,3,4,5,6,7,8,Count,Group 0
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,0.0
1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,3.0,0.0
2,2.0,1.0,0.0,2.0,1.0,0.0,1.0,0.0,7.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,7.0,0.0
3,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,7.0,0.0
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0