In [ ]:
#to prevent colab to automatically disconnect
import IPython
from google.colab import output

display(IPython.display.Javascript('''
 function ClickConnect(){
   btn = document.querySelector("colab-connect-button")
   if (btn != null){
     console.log("Click colab-connect-button");
     btn.click()
     }

   btn = document.getElementById('ok')
   if (btn != null){
     console.log("Click reconnect");
     btn.click()
     }
  }

setInterval(ClickConnect,60000)
'''))

print("Done.")

Done.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Step 1:Importing Libraries and Installing Dependencies**

In [ ]:
pip install keras-self-attention

Collecting keras-self-attention
  Downloading keras-self-attention-0.51.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras-self-attention) (2.0.2)
Building wheels for collected packages: keras-self-attention
  Building wheel for keras-self-attention (setup.py) ... done
  Created wheel for keras-self-attention: filename=keras_self_attention-0.51.0-py3-none-any.whl size=18895 sha256=d05b7e6f0e2b6d865419310cb7db606280bc64b17ec50103856bee2933d6185e
  Stored in directory: /root/.cache/pip/wheels/46/f9/96/709295c836133071c12a300729fed4027757f889c01695feea
Successfully built keras-self-attention
Installing collected packages: keras-self-attention
Successfully installed keras-self-attention-0.51.0

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.13.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.14.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
# For data processing
import numpy as np
import math
from math import sqrt

# For data processing and manipulation
import pandas as pd
import csv

# For date calculations
import datetime
import time

# For ploting data
import IPython
import IPython.display

import itertools
from itertools import cycle
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# For checking path
import os , gc
import csv
import json


from scipy.stats import hmean

from sklearn.metrics import mean_squared_error, mean_absolute_error


from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping , Callback
import tensorflow as tf
from tensorflow.keras import backend as K
from keras import backend

from tensorflow.keras.layers import *
from tensorflow.keras.layers import Dense , GRU ,Dropout , PReLU , RepeatVector ,TimeDistributed, Attention,LayerNormalization,Add
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, Bidirectional, GRU, Dropout, MultiHeadAttention, Add, LayerNormalization, TimeDistributed, Dense, GRU,Bidirectional,TimeDistributed, PReLU ,Add,BatchNormalization
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.utils import to_categorical , plot_model
from tensorflow.keras import regularizers, constraints, initializers, activations




from tensorflow.keras.layers import InputSpec

from keras_self_attention import SeqSelfAttention
from tensorflow.keras.layers import Concatenate

tf.get_logger().setLevel('ERROR')
mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

# **Step 2: Loading Dataset**

In [ ]:
#(paths in my personal drive)
model_save_path = r'/content/drive/MyDrive/Forecasting(without weather dataset)/3.Crime Forecasting/Trained_model_Files'
dataset_path = r'/content/drive/MyDrive/Forecasting(without weather dataset)/2.Preparing Dataset to feed Model/patrol_wise_crime_dataset'

In [ ]:
files = os.listdir(dataset_path)
files

['Central_1.csv',
 'Rampart_2.csv',
 'Southwest_3.csv',
 'Hollenbeck_4.csv',
 'Harbor_5.csv',
 'Hollywood_6.csv',
 'Wilshire_7.csv',
 'West LA_8.csv',
 'Van Nuys_9.csv',
 'West Valley_10.csv',
 'Northeast_11.csv',
 '77th Street_12.csv',
 'Newton_13.csv',
 'Pacific_14.csv',
 'N Hollywood_15.csv',
 'Foothill_16.csv',
 'Devonshire_17.csv',
 'Southeast_18.csv',
 'Mission_19.csv',
 'Olympic_20.csv',
 'Topanga_21.csv']

In [ ]:
#loading dataset
patrol_divisons = {}
dataset = {}
for file in files:
  name = file.split('_')[0]
  id = file.split('_')[1].split('.')[0]
  patrol_divisons[int(id)] = name
  dataset[int(id)] = pd.read_csv(os.path.join(dataset_path,file))


patrol_divisons = dict(sorted(patrol_divisons.items()))
patrol_divisons

{1: 'Central',
 2: 'Rampart',
 3: 'Southwest',
 4: 'Hollenbeck',
 5: 'Harbor',
 6: 'Hollywood',
 7: 'Wilshire',
 8: 'West LA',
 9: 'Van Nuys',
 10: 'West Valley',
 11: 'Northeast',
 12: '77th Street',
 13: 'Newton',
 14: 'Pacific',
 15: 'N Hollywood',
 16: 'Foothill',
 17: 'Devonshire',
 18: 'Southeast',
 19: 'Mission',
 20: 'Olympic',
 21: 'Topanga'}

In [ ]:
columns_in_dataset = dataset[1].columns
columns_in_dataset

Index(['Unnamed: 0', 'datetime', 'p_id', '1', '2', '3', '4', '5', '6', '7',
       '8', 'group 0', 'count', 'day sin', 'day cos', 'week sin', 'week cos',
       'year sin', 'year cos'],
      dtype='object')

In [ ]:
for key in dataset:
    if 'Unnamed: 0' in dataset[key].columns:
        dataset[key] = dataset[key].drop('Unnamed: 0', axis=1)

In [ ]:
dataset[1].head()

,datetime,p_id,1,2,3,4,5,6,7,8,group 0,count,day sin,day cos,week sin,week cos,year sin,year cos
0,2010-01-01 00:00:00,1,6.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,11.0,-4.416858e-12,1.000000e+00,0.781831,0.623490,0.005161,0.999987
1,2010-01-01 03:00:00,1,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,7.071068e-01,7.071068e-01,0.846724,0.532032,0.007311,0.999973
2,2010-01-01 06:00:00,1,0.0,0.0,0.0,12.0,1.0,0.0,0.0,1.0,0.0,14.0,1.000000e+00,6.980203e-12,0.900969,0.433884,0.009461,0.999955
3,2010-01-01 09:00:00,1,2.0,0.0,0.0,13.0,1.0,0.0,1.0,0.0,0.0,17.0,7.071068e-01,-7.071068e-01,0.943883,0.330279,0.011612,0.999933
4,2010-01-01 12:00:00,1,0.0,2.0,0.0,7.0,0.0,0.0,0.0,1.0,0.0,10.0,9.543547e-12,-1.000000e+00,0.974928,0.222521,0.013762,0.999905

In [ ]:
print(dataset[1]["count"].max())
print(dataset[1]["count"].min())

69.0
0.0

# **Step 3: Converting to Time Series data**

**Utility Functions**

In [ ]:
def train_test_val_split(dataset):
  columns_indices = {name:i for i,name in enumerate(dataset.columns)}
  n = len(dataset)

  #splitting dataset
  training_set = dataset[:int(n*0.7)]
  validation_set = dataset[int(n*0.7):int(n*0.9)]
  test_set = dataset[int(n*0.9):]

  num_features = dataset.shape[1]
  return training_set, validation_set, test_set, num_features, columns_indices

In [ ]:
class WindowGenerator():

    def __init__(self, input_width, label_width, shift,
               train_df, val_df, test_df,
               label_columns=None , shuffle=False , batch_size = 64):
        '''
        The __init__ method includes all the necessary logic for the input and label indices.
        Input:
            input_width : input width / window size
            label_width : output width
            shift : size of window shifting forward
            train_df : train dataset
            val_df : validation dataset
            test_df : test dataset
            label_columns ( Default = None) : Label Columns
            shuffle ( Default = False) : weather to shuffle data
            batch_size (Default = 64) : Batch Size
        Output: None
        Example :
            w2 = WindowGenerator(input_width=6, label_width=1, shift=1,
                     label_columns=['count'])
            w2

        '''
        # Store the raw data.
        self.train_df = train_df
        self.val_df = val_df
        self.test_df = test_df
        self.shuffle = shuffle
        self.batch_size = batch_size

        # Work out the label column indices.
        self.label_columns = label_columns
        if label_columns is not None:
            self.label_columns_indices = {name: i for i, name in
                                        enumerate(label_columns)}

        self.column_indices = {name: i for i, name in
                            enumerate(train_df.columns)}


        # Work out the window parameters.
        self.input_width = input_width
        self.label_width = label_width
        self.shift = shift

        self.total_window_size = input_width + shift

        self.input_slice = slice(0, input_width) #(start , stop)
        self.input_indices = np.arange(self.total_window_size)[self.input_slice]

        self.label_start = self.total_window_size - self.label_width
        self.labels_slice = slice(self.label_start, None)
        self.label_indices = np.arange(self.total_window_size)[self.labels_slice]

    def __repr__(self):
        return '\n'.join([
            f'Total window size: {self.total_window_size}',
            f'Input indices: {self.input_indices}',
            f'Label indices: {self.label_indices}',
            f'Label column name(s): {self.label_columns}'])

    def split_window(self, features):

        inputs = features[:, self.input_slice, :]
        labels = features[:, self.labels_slice, :]
        #taking only the labels that are presentin the label_columns
        if self.label_columns is not None:
            labels = tf.stack([labels[:, :, self.column_indices[name]] for name in self.label_columns],axis=-1)

        # Slicing doesn't preserve static shape information, so set the shapes
        # manually. This way the `tf.data.Datasets` are easier to inspect.
        inputs.set_shape([None, self.input_width, None])
        labels.set_shape([None, self.label_width, None])

        return inputs, labels



    def make_dataset(self, data):

        data = np.array(data, dtype=np.float32)
        ds = tf.keras.preprocessing.timeseries_dataset_from_array(
            data=data,
            targets=None,
            sequence_length=self.total_window_size,
            sequence_stride=1,
            shuffle=self.shuffle,
            batch_size=self.batch_size,)
        ds = ds.map(self.split_window)
        return ds


    def create_dataset2(self , map_df , reshape=True):
      x = []
      y = []
      for res in iter(map_df):
        inputs, labels = res
        if(len(inputs)==64):
          x.append(inputs)
          y.append(labels)

      x = np.array(x)
      y = np.array(y)
      if(reshape):
        x = x.reshape(-1, x.shape[-2] , x.shape[-1])
        y = y.reshape(-1 , y.shape[-2] , y.shape[-1])
      return x , y

    '''
    properties for accessing  training, validation and test data as tf.data.Datasets using the above make_dataset method.
    Also a standard example batch for easy access and plotting
    '''

    @property
    def train(self):
        return self.make_dataset(self.train_df)

    @property
    def val(self):
        return self.make_dataset(self.val_df)

    @property
    def test(self):
        return self.make_dataset(self.test_df)

In [ ]:
def create_data(train , test , val , columns):
    '''
    Create dataset from main train , test , val with given columns
    '''
    if(columns==None):
        columns = train.columns
    new_train = train[columns]
    new_test = test[columns]
    new_val = val[columns]
    return new_train , new_test , new_val

In [ ]:
def save_history(history , path):
    # convert the history.history dict to a pandas DataFrame:
    hist_df = pd.DataFrame(history.history)
    # or save to csv:
    hist_csv_file = path
    with open(hist_csv_file, mode='w') as f:
        hist_df.to_json(f)

def get_history(path):
	with open(path) as json_file:
		data = json.load(json_file)
		return data

def save_model_weights(model , path):
  model.save_weights(path)

Functions for Model Compiling and Fitting

In [ ]:
def compileModel(model):

        lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
          initial_learning_rate=1e-4,
          decay_steps=1000,
          decay_rate=0.96,
          staircase=True,
      )
        optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

        model.compile(loss=tf.losses.MeanAbsoluteError(),optimizer = optimizer,
                   metrics =[ tf.keras.metrics.RootMeanSquaredError(name='rmse'),
                              tf.keras.metrics.MeanAbsoluteError(name='mae')])
        return model

MAX_EPOCHS = 30

def fit(model,ROOTPATH, modelPath , historyPath , window=None, name=None , patience = 5):
    '''
    Compile and fit a model
    '''

    modelPathPar = os.path.join(ROOTPATH,modelPath)
    historyPathPar = os.path.join(ROOTPATH,historyPath)

    #Creating a file to store model and it's history
    if (name!=None):
        model_path = os.path.join(modelPathPar,name+".keras")
        history_path = os.path.join(historyPathPar,name+".json")

        if not os.path.exists(modelPathPar):
            os.makedirs(modelPathPar)
        if not os.path.exists(historyPathPar):
            os.makedirs(historyPathPar)

    if (name!=None and os.path.exists(model_path)):
      print("Loaded Pre Trained Model")
      modelOld = tf.keras.models.load_model(model_path)
      model.set_weights(modelOld.get_weights())
      del modelOld
      history = get_history(history_path)
      return model , history



    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=patience)

    history = model.fit(window.train, epochs=MAX_EPOCHS,batch_size = 64,validation_data=window.val,
                        callbacks=[early_stopping],verbose=1)


    if(name!=None):
      model.save(model_path)
      save_history(history , history_path)

    return model , history.history

Function to save  metric values

In [ ]:
def build_metrics_dataframe(test_metrics_dict, val_metrics_dict, patrol_divisions_dict):
    """
    Converts performance dictionaries into a structured DataFrame.

    Parameters:
        test_metrics_dict (dict): Dict of test evaluation results {division_id: [loss, rmse, mae]}
        val_metrics_dict (dict): Dict of val evaluation results {division_id: [loss, rmse, mae]}
        patrol_divisions_dict (dict): Dict mapping division_id to division name

    Returns:
        pd.DataFrame: DataFrame with division names as rows and metrics as columns
    """
    rows = []

    for div_id in test_metrics_dict.keys():
        div_name = patrol_divisions_dict[int(div_id)]
        test = test_metrics_dict[div_id]
        val = val_metrics_dict[div_id]

        rows.append({
            "Division": div_name,
            "test rmse": test[1],
            "test mae": test[2],
            "val rmse": val[1],
            "val mae": val[2]
        })

    df = pd.DataFrame(rows)
    df.set_index("Division", inplace=True)
    return df

In [ ]:
#without temperature
general_indexs = ['1', '2', '3', '4', '5', '6', '7','8', 'count',
           'day sin', 'day cos', 'week sin', 'week cos',
           'year sin', 'year cos', 'group 0']

x_col = ['day sin' , 'day cos' , 'year sin' , 'year cos' , 'week cos' , 'week sin' ,'datetime']

def generate_window(df_now, ret_test = 0):
    train_df , val_df , test_df , num_features_df , column_indices_df = train_test_val_split(df_now)
    train_df , test_df , val_df = create_data(train_df , test_df , val_df , general_indexs)
    y_col = []

    #storing label columns
    for i in train_df.columns:
        if (i in x_col):
            continue
        y_col.append(i)

    #creating window generator object
    wide_window_all = WindowGenerator(train_df=train_df, test_df=test_df , val_df=val_df,
        input_width=24, label_width=24, shift=1,
        label_columns=y_col)

    if (ret_test == 1):
      return wide_window_all, test_df
    else:
      return wide_window_all

**1.Multi Head Attention CNN Bi GRU**

In [ ]:
input_layer = Input(shape=(24, 16))  # 24 time steps, 16 features

# ----- CNN Block 1 -----
x = Conv1D(filters=64, kernel_size=3, padding='same')(input_layer)
x = BatchNormalization()(x)
x = Activation('relu')(x)

# ----- CNN Block 2 -----
x = Conv1D(filters=64, kernel_size=3, padding='same')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)

# ----- CNN Block 3 -----
x = Conv1D(filters=128, kernel_size=3, padding='same')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)

# ----- BiGRU -----
x_bi = Bidirectional(GRU(128, return_sequences=True))(x)
x_bi = Dropout(0.3)(x_bi)

# ----- Multi-Head Attention -----
attn_output = MultiHeadAttention(num_heads=4, key_dim=64)(x_bi, x_bi)
attn_output = Dropout(0.3)(attn_output)

# ----- Residual Connection -----
res_1 = Add()([x_bi, attn_output])
res_1 = LayerNormalization()(res_1)

# ----- Feedforward + Residual -----
ff = TimeDistributed(Dense(64, activation='relu'))(res_1)
proj = TimeDistributed(Dense(64))(res_1)
ff = Dropout(0.2)(ff)
res_2 = Add()([proj, ff])
res_2 = LayerNormalization()(res_2)

# ----- Output Layer -----
output = TimeDistributed(Dense(10))(res_2)

model = Model(inputs=input_layer, outputs=output)

In [ ]:
val_performance_of_mh_attn_cnn_bi_gru = {}
performance_of_mh_attn_cnn_bi_gru = {}
histories_of_mh_attn_cnn_bi_gru = {}
mh_attn_cnn_bi_gru_model = compileModel(model)
save_path = os.path.join(model_save_path,"Multi Head Attention CNN Bi GRU")
for x in patrol_divisons.keys():
        wide_window_all = generate_window(dataset[x])
        print(x,patrol_divisons[x])
        x = str(x)
        trained_mh_attn_cnn_bi_gru_model , history  = fit(
            mh_attn_cnn_bi_gru_model,save_path, "mh_attn_cnn_bi_gru_model_files" , "mh_attn_cnn_bi_gru_history_files" , name='mh_attn_cnn_bi_gru_'+x , window=wide_window_all)
        histories_of_mh_attn_cnn_bi_gru['bd_'+x] = history
        val_performance_of_mh_attn_cnn_bi_gru[x] = trained_mh_attn_cnn_bi_gru_model.evaluate(wide_window_all.val)
        performance_of_mh_attn_cnn_bi_gru[x] = trained_mh_attn_cnn_bi_gru_model.evaluate(wide_window_all.test)

1 Central
Epoch 1/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 28s 31ms/step - loss: 0.6074 - mae: 0.6074 - rmse: 0.9403 - val_loss: 0.4492 - val_mae: 0.4492 - val_rmse: 0.8293
Epoch 2/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.2816 - mae: 0.2816 - rmse: 0.5193 - val_loss: 0.3748 - val_mae: 0.3748 - val_rmse: 0.7368
Epoch 3/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.2271 - mae: 0.2271 - rmse: 0.4667 - val_loss: 0.3339 - val_mae: 0.3339 - val_rmse: 0.6885
Epoch 4/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 0.2035 - mae: 0.2035 - rmse: 0.4487 - val_loss: 0.3095 - val_mae: 0.3095 - val_rmse: 0.6583
Epoch 5/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 18s 28ms/step - loss: 0.1897 - mae: 0.1897 - rmse: 0.4380 - val_loss: 0.2911 - val_mae: 0.2911 - val_rmse: 0.6355
Epoch 6/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 14s 30ms/step - loss: 0.1800 - mae: 0.1800 - rmse: 0.4294 - val_loss: 0.2749 - val_mae: 0.2749 - val_rmse: 0.6162
Epoch 7/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1731 - mae: 0.1731 - rmse: 0.4233 - val_loss: 0.2628 - val_mae: 0.2628 - val_rmse: 0.6001
Epoch 8/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1686 - mae: 0.1686 - rmse: 0.4180 - val_loss: 0.2501 - val_mae: 0.2501 - val_rmse: 0.5818
Epoch 9/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1646 - mae: 0.1646 - rmse: 0.4102 - val_loss: 0.2362 - val_mae: 0.2362 - val_rmse: 0.5634
Epoch 10/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1604 - mae: 0.1604 - rmse: 0.4038 - val_loss: 0.2276 - val_mae: 0.2276 - val_rmse: 0.5539
Epoch 11/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - loss: 0.1572 - mae: 0.1572 - rmse: 0.4008 - val_loss: 0.2187 - val_mae: 0.2187 - val_rmse: 0.5446
Epoch 12/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1551 - mae: 0.1551 - rmse: 0.3995 - val_loss: 0.2140 - val_mae: 0.2140 - val_rmse: 0.5390
Epoch 13/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1531 - mae: 0.1531 - rmse: 0.3977 - val_loss: 0.2082 - val_mae: 0.2082 - val_rmse: 0.5326
Epoch 14/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1517 - mae: 0.1517 - rmse: 0.3967 - val_loss: 0.2062 - val_mae: 0.2062 - val_rmse: 0.5298
Epoch 15/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1498 - mae: 0.1498 - rmse: 0.3944 - val_loss: 0.2019 - val_mae: 0.2019 - val_rmse: 0.5258
Epoch 16/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1489 - mae: 0.1489 - rmse: 0.3940 - val_loss: 0.2015 - val_mae: 0.2015 - val_rmse: 0.5248
Epoch 17/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - loss: 0.1469 - mae: 0.1469 - rmse: 0.3914 - val_loss: 0.1967 - val_mae: 0.1967 - val_rmse: 0.5194
Epoch 18/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1459 - mae: 0.1459 - rmse: 0.3904 - val_loss: 0.1972 - val_mae: 0.1972 - val_rmse: 0.5191
Epoch 19/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1443 - mae: 0.1443 - rmse: 0.3887 - val_loss: 0.1951 - val_mae: 0.1951 - val_rmse: 0.5163
Epoch 20/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1433 - mae: 0.1433 - rmse: 0.3876 - val_loss: 0.1931 - val_mae: 0.1931 - val_rmse: 0.5138
Epoch 21/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - loss: 0.1416 - mae: 0.1416 - rmse: 0.3852 - val_loss: 0.1916 - val_mae: 0.1916 - val_rmse: 0.5126
Epoch 22/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1406 - mae: 0.1406 - rmse: 0.3840 - val_loss: 0.1911 - val_mae: 0.1911 - val_rmse: 0.5111
Epoch 23/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1395 - mae: 0.1395 - rmse: 0.3827 - val_loss: 0.1882 - val_mae: 0.1882 - val_rmse: 0.5083
Epoch 24/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 26ms/step - loss: 0.1388 - mae: 0.1388 - rmse: 0.3819 - val_loss: 0.1882 - val_mae: 0.1882 - val_rmse: 0.5082
Epoch 25/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1371 - mae: 0.1371 - rmse: 0.3793 - val_loss: 0.1852 - val_mae: 0.1852 - val_rmse: 0.5046
Epoch 26/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - loss: 0.1363 - mae: 0.1363 - rmse: 0.3785 - val_loss: 0.1865 - val_mae: 0.1865 - val_rmse: 0.5058
Epoch 27/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1350 - mae: 0.1350 - rmse: 0.3766 - val_loss: 0.1856 - val_mae: 0.1856 - val_rmse: 0.5044
Epoch 28/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 14s 30ms/step - loss: 0.1345 - mae: 0.1345 - rmse: 0.3758 - val_loss: 0.1837 - val_mae: 0.1837 - val_rmse: 0.5025
Epoch 29/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1331 - mae: 0.1331 - rmse: 0.3739 - val_loss: 0.1840 - val_mae: 0.1840 - val_rmse: 0.5026
Epoch 30/30
483/483 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1323 - mae: 0.1323 - rmse: 0.3728 - val_loss: 0.1834 - val_mae: 0.1834 - val_rmse: 0.5020
138/138 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.1601 - mae: 0.1601 - rmse: 0.4429
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2357 - mae: 0.2357 - rmse: 0.7128
2 Rampart
Epoch 1/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1304 - mae: 0.1304 - rmse: 0.3292 - val_loss: 0.1020 - val_mae: 0.1020 - val_rmse: 0.3239
Epoch 2/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 0.1223 - mae: 0.1223 - rmse: 0.3203 - val_loss: 0.1006 - val_mae: 0.1006 - val_rmse: 0.3234
Epoch 3/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 27ms/step - loss: 0.1203 - mae: 0.1203 - rmse: 0.3185 - val_loss: 0.1001 - val_mae: 0.1001 - val_rmse: 0.3231
Epoch 4/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1188 - mae: 0.1188 - rmse: 0.3171 - val_loss: 0.0999 - val_mae: 0.0999 - val_rmse: 0.3226
Epoch 5/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.1173 - mae: 0.1173 - rmse: 0.3154 - val_loss: 0.0986 - val_mae: 0.0986 - val_rmse: 0.3217
Epoch 6/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1162 - mae: 0.1162 - rmse: 0.3141 - val_loss: 0.0985 - val_mae: 0.0985 - val_rmse: 0.3218
Epoch 7/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1150 - mae: 0.1150 - rmse: 0.3129 - val_loss: 0.0974 - val_mae: 0.0974 - val_rmse: 0.3210
Epoch 8/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1138 - mae: 0.1138 - rmse: 0.3113 - val_loss: 0.0974 - val_mae: 0.0974 - val_rmse: 0.3211
Epoch 9/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1128 - mae: 0.1128 - rmse: 0.3103 - val_loss: 0.0970 - val_mae: 0.0970 - val_rmse: 0.3209
Epoch 10/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1119 - mae: 0.1119 - rmse: 0.3095 - val_loss: 0.0964 - val_mae: 0.0964 - val_rmse: 0.3201
Epoch 11/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - loss: 0.1109 - mae: 0.1109 - rmse: 0.3085 - val_loss: 0.0961 - val_mae: 0.0961 - val_rmse: 0.3198
Epoch 12/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1102 - mae: 0.1102 - rmse: 0.3076 - val_loss: 0.0960 - val_mae: 0.0960 - val_rmse: 0.3198
Epoch 13/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1094 - mae: 0.1094 - rmse: 0.3063 - val_loss: 0.0950 - val_mae: 0.0950 - val_rmse: 0.3191
Epoch 14/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.1085 - mae: 0.1085 - rmse: 0.3054 - val_loss: 0.0951 - val_mae: 0.0951 - val_rmse: 0.3191
Epoch 15/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1078 - mae: 0.1078 - rmse: 0.3044 - val_loss: 0.0950 - val_mae: 0.0950 - val_rmse: 0.3188
Epoch 16/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 30ms/step - loss: 0.1072 - mae: 0.1072 - rmse: 0.3039 - val_loss: 0.0947 - val_mae: 0.0947 - val_rmse: 0.3186
Epoch 17/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 19s 28ms/step - loss: 0.1066 - mae: 0.1066 - rmse: 0.3031 - val_loss: 0.0946 - val_mae: 0.0946 - val_rmse: 0.3182
Epoch 18/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1058 - mae: 0.1058 - rmse: 0.3019 - val_loss: 0.0946 - val_mae: 0.0946 - val_rmse: 0.3183
Epoch 19/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 0.1053 - mae: 0.1053 - rmse: 0.3014 - val_loss: 0.0939 - val_mae: 0.0939 - val_rmse: 0.3178
Epoch 20/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1047 - mae: 0.1047 - rmse: 0.3008 - val_loss: 0.0938 - val_mae: 0.0938 - val_rmse: 0.3176
Epoch 21/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1042 - mae: 0.1042 - rmse: 0.2999 - val_loss: 0.0936 - val_mae: 0.0936 - val_rmse: 0.3173
Epoch 22/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1037 - mae: 0.1037 - rmse: 0.2993 - val_loss: 0.0937 - val_mae: 0.0937 - val_rmse: 0.3174
Epoch 23/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1031 - mae: 0.1031 - rmse: 0.2987 - val_loss: 0.0929 - val_mae: 0.0929 - val_rmse: 0.3169
Epoch 24/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.1027 - mae: 0.1027 - rmse: 0.2982 - val_loss: 0.0926 - val_mae: 0.0926 - val_rmse: 0.3165
Epoch 25/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1022 - mae: 0.1022 - rmse: 0.2975 - val_loss: 0.0928 - val_mae: 0.0928 - val_rmse: 0.3166
Epoch 26/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1017 - mae: 0.1017 - rmse: 0.2966 - val_loss: 0.0930 - val_mae: 0.0930 - val_rmse: 0.3168
Epoch 27/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1014 - mae: 0.1014 - rmse: 0.2963 - val_loss: 0.0924 - val_mae: 0.0924 - val_rmse: 0.3163
Epoch 28/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.1011 - mae: 0.1011 - rmse: 0.2960 - val_loss: 0.0923 - val_mae: 0.0923 - val_rmse: 0.3161
Epoch 29/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1006 - mae: 0.1006 - rmse: 0.2953 - val_loss: 0.0925 - val_mae: 0.0925 - val_rmse: 0.3164
Epoch 30/30
482/482 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.1003 - mae: 0.1003 - rmse: 0.2952 - val_loss: 0.0923 - val_mae: 0.0923 - val_rmse: 0.3160
138/138 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0835 - mae: 0.0835 - rmse: 0.2723
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1102 - mae: 0.1102 - rmse: 0.4008
3 Southwest
Epoch 1/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1697 - mae: 0.1697 - rmse: 0.4988 - val_loss: 0.1650 - val_mae: 0.1650 - val_rmse: 0.5625
Epoch 2/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1621 - mae: 0.1621 - rmse: 0.4828 - val_loss: 0.1643 - val_mae: 0.1643 - val_rmse: 0.5577
Epoch 3/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1608 - mae: 0.1608 - rmse: 0.4799 - val_loss: 0.1625 - val_mae: 0.1625 - val_rmse: 0.5531
Epoch 4/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1594 - mae: 0.1594 - rmse: 0.4766 - val_loss: 0.1626 - val_mae: 0.1626 - val_rmse: 0.5515
Epoch 5/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1582 - mae: 0.1582 - rmse: 0.4742 - val_loss: 0.1608 - val_mae: 0.1608 - val_rmse: 0.5485
Epoch 6/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1568 - mae: 0.1568 - rmse: 0.4714 - val_loss: 0.1605 - val_mae: 0.1605 - val_rmse: 0.5471
Epoch 7/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1558 - mae: 0.1558 - rmse: 0.4692 - val_loss: 0.1593 - val_mae: 0.1593 - val_rmse: 0.5451
Epoch 8/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1546 - mae: 0.1546 - rmse: 0.4667 - val_loss: 0.1594 - val_mae: 0.1594 - val_rmse: 0.5438
Epoch 9/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1540 - mae: 0.1540 - rmse: 0.4655 - val_loss: 0.1575 - val_mae: 0.1575 - val_rmse: 0.5417
Epoch 10/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1532 - mae: 0.1532 - rmse: 0.4635 - val_loss: 0.1565 - val_mae: 0.1565 - val_rmse: 0.5398
Epoch 11/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1520 - mae: 0.1520 - rmse: 0.4612 - val_loss: 0.1561 - val_mae: 0.1561 - val_rmse: 0.5388
Epoch 12/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1515 - mae: 0.1515 - rmse: 0.4602 - val_loss: 0.1550 - val_mae: 0.1550 - val_rmse: 0.5372
Epoch 13/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 22s 30ms/step - loss: 0.1508 - mae: 0.1508 - rmse: 0.4589 - val_loss: 0.1535 - val_mae: 0.1535 - val_rmse: 0.5354
Epoch 14/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 19s 28ms/step - loss: 0.1501 - mae: 0.1501 - rmse: 0.4573 - val_loss: 0.1538 - val_mae: 0.1538 - val_rmse: 0.5350
Epoch 15/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1494 - mae: 0.1494 - rmse: 0.4558 - val_loss: 0.1518 - val_mae: 0.1518 - val_rmse: 0.5330
Epoch 16/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1487 - mae: 0.1487 - rmse: 0.4544 - val_loss: 0.1522 - val_mae: 0.1522 - val_rmse: 0.5327
Epoch 17/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1482 - mae: 0.1482 - rmse: 0.4534 - val_loss: 0.1495 - val_mae: 0.1495 - val_rmse: 0.5301
Epoch 18/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1473 - mae: 0.1473 - rmse: 0.4521 - val_loss: 0.1499 - val_mae: 0.1499 - val_rmse: 0.5298
Epoch 19/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1467 - mae: 0.1467 - rmse: 0.4507 - val_loss: 0.1481 - val_mae: 0.1481 - val_rmse: 0.5280
Epoch 20/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1463 - mae: 0.1463 - rmse: 0.4499 - val_loss: 0.1483 - val_mae: 0.1483 - val_rmse: 0.5276
Epoch 21/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.1458 - mae: 0.1458 - rmse: 0.4490 - val_loss: 0.1469 - val_mae: 0.1469 - val_rmse: 0.5259
Epoch 22/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.1453 - mae: 0.1453 - rmse: 0.4483 - val_loss: 0.1470 - val_mae: 0.1470 - val_rmse: 0.5253
Epoch 23/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1447 - mae: 0.1447 - rmse: 0.4469 - val_loss: 0.1442 - val_mae: 0.1442 - val_rmse: 0.5231
Epoch 24/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1444 - mae: 0.1444 - rmse: 0.4459 - val_loss: 0.1443 - val_mae: 0.1443 - val_rmse: 0.5228
Epoch 25/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.1437 - mae: 0.1437 - rmse: 0.4448 - val_loss: 0.1434 - val_mae: 0.1434 - val_rmse: 0.5217
Epoch 26/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 0.1434 - mae: 0.1434 - rmse: 0.4444 - val_loss: 0.1429 - val_mae: 0.1429 - val_rmse: 0.5209
Epoch 27/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1429 - mae: 0.1429 - rmse: 0.4433 - val_loss: 0.1423 - val_mae: 0.1423 - val_rmse: 0.5199
Epoch 28/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1427 - mae: 0.1427 - rmse: 0.4424 - val_loss: 0.1414 - val_mae: 0.1414 - val_rmse: 0.5190
Epoch 29/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1420 - mae: 0.1420 - rmse: 0.4418 - val_loss: 0.1403 - val_mae: 0.1403 - val_rmse: 0.5179
Epoch 30/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.1418 - mae: 0.1418 - rmse: 0.4410 - val_loss: 0.1396 - val_mae: 0.1396 - val_rmse: 0.5170
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1273 - mae: 0.1273 - rmse: 0.3649
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1354 - mae: 0.1354 - rmse: 0.3679
4 Hollenbeck
Epoch 1/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - loss: 0.1038 - mae: 0.1038 - rmse: 0.2835 - val_loss: 0.0795 - val_mae: 0.0795 - val_rmse: 0.2458
Epoch 2/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 0.0966 - mae: 0.0966 - rmse: 0.2761 - val_loss: 0.0766 - val_mae: 0.0766 - val_rmse: 0.2435
Epoch 3/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.0947 - mae: 0.0947 - rmse: 0.2740 - val_loss: 0.0752 - val_mae: 0.0752 - val_rmse: 0.2423
Epoch 4/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.0934 - mae: 0.0934 - rmse: 0.2726 - val_loss: 0.0740 - val_mae: 0.0740 - val_rmse: 0.2415
Epoch 5/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.0924 - mae: 0.0924 - rmse: 0.2714 - val_loss: 0.0733 - val_mae: 0.0733 - val_rmse: 0.2410
Epoch 6/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0917 - mae: 0.0917 - rmse: 0.2710 - val_loss: 0.0727 - val_mae: 0.0727 - val_rmse: 0.2406
Epoch 7/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 22s 31ms/step - loss: 0.0909 - mae: 0.0909 - rmse: 0.2700 - val_loss: 0.0723 - val_mae: 0.0723 - val_rmse: 0.2404
Epoch 8/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - loss: 0.0904 - mae: 0.0904 - rmse: 0.2693 - val_loss: 0.0716 - val_mae: 0.0716 - val_rmse: 0.2401
Epoch 9/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 19s 29ms/step - loss: 0.0899 - mae: 0.0899 - rmse: 0.2690 - val_loss: 0.0714 - val_mae: 0.0714 - val_rmse: 0.2400
Epoch 10/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0894 - mae: 0.0894 - rmse: 0.2685 - val_loss: 0.0707 - val_mae: 0.0707 - val_rmse: 0.2396
Epoch 11/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.0890 - mae: 0.0890 - rmse: 0.2680 - val_loss: 0.0707 - val_mae: 0.0707 - val_rmse: 0.2398
Epoch 12/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0887 - mae: 0.0887 - rmse: 0.2683 - val_loss: 0.0704 - val_mae: 0.0704 - val_rmse: 0.2397
Epoch 13/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - loss: 0.0884 - mae: 0.0884 - rmse: 0.2676 - val_loss: 0.0704 - val_mae: 0.0704 - val_rmse: 0.2398
Epoch 14/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.0880 - mae: 0.0880 - rmse: 0.2670 - val_loss: 0.0699 - val_mae: 0.0699 - val_rmse: 0.2397
Epoch 15/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0876 - mae: 0.0876 - rmse: 0.2669 - val_loss: 0.0698 - val_mae: 0.0698 - val_rmse: 0.2397
Epoch 16/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0875 - mae: 0.0875 - rmse: 0.2669 - val_loss: 0.0695 - val_mae: 0.0695 - val_rmse: 0.2397
Epoch 17/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.0872 - mae: 0.0872 - rmse: 0.2666 - val_loss: 0.0695 - val_mae: 0.0695 - val_rmse: 0.2396
Epoch 18/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0869 - mae: 0.0869 - rmse: 0.2661 - val_loss: 0.0691 - val_mae: 0.0691 - val_rmse: 0.2396
Epoch 19/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.0867 - mae: 0.0867 - rmse: 0.2664 - val_loss: 0.0693 - val_mae: 0.0693 - val_rmse: 0.2398
Epoch 20/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.0864 - mae: 0.0864 - rmse: 0.2658 - val_loss: 0.0691 - val_mae: 0.0691 - val_rmse: 0.2397
Epoch 21/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0862 - mae: 0.0862 - rmse: 0.2655 - val_loss: 0.0693 - val_mae: 0.0693 - val_rmse: 0.2400
Epoch 22/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.0860 - mae: 0.0860 - rmse: 0.2653 - val_loss: 0.0689 - val_mae: 0.0689 - val_rmse: 0.2397
Epoch 23/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.0859 - mae: 0.0859 - rmse: 0.2656 - val_loss: 0.0691 - val_mae: 0.0691 - val_rmse: 0.2400
Epoch 24/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0857 - mae: 0.0857 - rmse: 0.2655 - val_loss: 0.0688 - val_mae: 0.0688 - val_rmse: 0.2400
Epoch 25/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.0854 - mae: 0.0854 - rmse: 0.2650 - val_loss: 0.0688 - val_mae: 0.0688 - val_rmse: 0.2400
Epoch 26/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - loss: 0.0854 - mae: 0.0854 - rmse: 0.2650 - val_loss: 0.0686 - val_mae: 0.0686 - val_rmse: 0.2400
Epoch 27/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 28ms/step - loss: 0.0852 - mae: 0.0852 - rmse: 0.2650 - val_loss: 0.0686 - val_mae: 0.0686 - val_rmse: 0.2400
Epoch 28/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0850 - mae: 0.0850 - rmse: 0.2648 - val_loss: 0.0685 - val_mae: 0.0685 - val_rmse: 0.2400
Epoch 29/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0848 - mae: 0.0848 - rmse: 0.2644 - val_loss: 0.0684 - val_mae: 0.0684 - val_rmse: 0.2401
Epoch 30/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.0848 - mae: 0.0848 - rmse: 0.2647 - val_loss: 0.0683 - val_mae: 0.0683 - val_rmse: 0.2401
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0661 - mae: 0.0661 - rmse: 0.2276
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0627 - mae: 0.0627 - rmse: 0.2077
5 Harbor
Epoch 1/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1064 - mae: 0.1064 - rmse: 0.3194 - val_loss: 0.0711 - val_mae: 0.0711 - val_rmse: 0.2542
Epoch 2/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1038 - mae: 0.1038 - rmse: 0.3157 - val_loss: 0.0710 - val_mae: 0.0710 - val_rmse: 0.2538
Epoch 3/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 0.1031 - mae: 0.1031 - rmse: 0.3150 - val_loss: 0.0710 - val_mae: 0.0710 - val_rmse: 0.2536
Epoch 4/30
486/486 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.1026 - mae: 0.1026 - rmse: 0.3142 - val_loss: 0.0708 - val_mae: 0.0708 - val_rmse: 0.2534
Epoch 5/30

In [ ]:
# Call the function after training is done
mh_attn_cnn_bi_gru_results_df = build_metrics_dataframe(
     performance_of_mh_attn_cnn_bi_gru,
    val_performance_of_mh_attn_cnn_bi_gru,
    patrol_divisons
)
csv_path = os.path.join(save_path,"mh_attn_bi_cnn_gru_results_1.csv")
mh_attn_cnn_bi_gru_results_df.to_csv(csv_path)

In [ ]:
mh_attn_cnn_bi_gru_results_df.head(21)

             test rmse  test mae  val rmse   val mae
Division
Central       0.734771  0.220938  0.502036  0.183389
Rampart       0.416581  0.107550  0.315990  0.092293
Southwest     0.392695  0.139872  0.517011  0.139608
Hollenbeck    0.186770  0.055708  0.240148  0.068322
Harbor        0.206728  0.061339  0.253156  0.070763
Hollywood     0.264965  0.081471  0.310172  0.100009
Wilshire      0.298715  0.110663  0.335209  0.132374
West LA       0.213828  0.060957  0.264133  0.083430
Van Nuys      0.209289  0.063126  0.244397  0.075294
West Valley   0.207974  0.060079  0.259444  0.077380
Northeast     0.213647  0.062865  0.244522  0.074135
77th Street   0.314859  0.131115  0.575814  0.159285
Newton        0.333890  0.115679  0.371585  0.104814
Pacific       0.314858  0.122795  0.331442  0.127243
N Hollywood   0.404441  0.136557  0.319665  0.123497
Foothill      0.213694  0.087809  0.260275  0.086832
Devonshire    0.247296  0.096916  0.279894  0.098724
Southeast     0.286612  0.116546  0.557605  0.140475
Mission       0.247808  0.106049  0.334557  0.105872
Olympic       0.330625  0.112347  0.306790  0.101586
Topanga       0.248702  0.102770  0.288275  0.103779

**Testing model trained on Central patrol divison**

In [ ]:
model = load_model(r'/content/drive/MyDrive/Crime Prediction/LA/Project Tasks(Codes)/Forecasting/3.Multi-Modal Fusion/FLF/Trained_model_files/Multi Head Attention Bi GRU/mh_attn_bi_gru_model_files/mh_attn_bi_gru_all_feature_3.keras')

In [ ]:
wide_window = generate_window(dataset[3])

In [ ]:
test_data = wide_window.test

In [ ]:

# Unbatch and convert to NumPy arrays
x_test_list = []
y_test_list = []

for x, y in test_data.unbatch():
    x_test_list.append(x.numpy())
    y_test_list.append(y.numpy())

# Convert lists to NumPy arrays
x_test = np.array(x_test_list)
y_test = np.array(y_test_list)

print("x_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)

x_test shape: (4178, 24, 16)
y_test shape: (4178, 24, 10)

In [ ]:
# Get predicted y values
y_pred = model.predict(x_test)
y_pred = np.round(np.maximum(y_pred, 0))
print("y_pred shape:", y_pred.shape)

131/131 ━━━━━━━━━━━━━━━━━━━━ 8s 26ms/step
y_pred shape: (4178, 24, 10)

In [ ]:
# Number of samples you want to inspect
num_samples = 5

# Create a list to store the comparison DataFrames
comparison_list = []

# Loop over the first `num_samples`
for i in range(num_samples):
    true_vals = y_test[i]   # shape: (24, 10)
    pred_vals = y_pred[i]   # shape: (24, 10)

    # Column names for better context
    columns = ['1','2','3','4','5','6','7','8','Count','Group 0']  # Adjust if needed

    df_true = pd.DataFrame(true_vals, columns=[f"{col}" for col in columns])
    df_pred = pd.DataFrame(pred_vals, columns=[f"{col}" for col in columns])

    df_both = pd.concat([df_true, df_pred], axis=1)
    comparison_list.append(df_both)

# Combine all comparisons into one DataFrame
full_comparison = pd.concat(comparison_list, axis=0)

# Reset index
full_comparison.reset_index(drop=True, inplace=True)

In [ ]:
full_comparison.head()

,1,2,3,4,5,6,7,8,Count,Group 0,1,2,3,4,5,6,7,8,Count,Group 0
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,0.0
1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,3.0,0.0
2,2.0,1.0,0.0,2.0,1.0,0.0,1.0,0.0,7.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,7.0,0.0
3,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,7.0,0.0
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0